CREATE DATABASE IF NOT EXISTS UserDB
	DEFAULT CHARACTER SET = utf8mb3;
CREATE DATABASE IF NOT EXISTS Posts
	DEFAULT CHARACTER SET = utf8mb3;
CREATE DATABASE IF NOT EXISTS Actions
	DEFAULT CHARACTER SET = utf8mb3;
CREATE DATABASE IF NOT EXISTS Comments
	DEFAULT CHARACTER SET = utf8mb3;


CREATE USER imgcat_jwt
IDENTIFIED BY <password here>
WITH
	MAX_STATEMENT_TIME 1;

CREATE USER imgcat_posts
IDENTIFIED BY <password here>
WITH
	MAX_STATEMENT_TIME 5;

CREATE USER imgcat_mods
IDENTIFIED BY <password here>
WITH
	MAX_STATEMENT_TIME 5;

CREATE USER imgcat_system
IDENTIFIED BY <password here>
WITH
	MAX_STATEMENT_TIME 5;