
export function GetCountryCodes() {
	return [
	{v:"AD",k:"Andorra"},
	{v:"AE",k:"United Arab Emirates"},
	{v:"AF",k:"Afghanistan"},
	{v:"AG",k:"Antigua and Barbuda"},
	{v:"AI",k:"Anguilla"},
	{v:"AL",k:"Albania"},
	{v:"AM",k:"Armenia"},
	{v:"AO",k:"Angola"},
	{v:"AQ",k:"Antarctica"},
	{v:"AR",k:"Argentina"},
	{v:"AS",k:"American Samoa"},
	{v:"AT",k:"Austria"},
	{v:"AU",k:"Australia"},
	{v:"AW",k:"Aruba"},
	{v:"AX",k:"Åland Islands"},
	{v:"AZ",k:"Azerbaijan"},
	{v:"BA",k:"Bosnia and Herzegovina"},
	{v:"BB",k:"Barbados"},
	{v:"BD",k:"Bangladesh"},
	{v:"BE",k:"Belgium"},
	{v:"BF",k:"Burkina Faso"},
	{v:"BG",k:"Bulgaria"},
	{v:"BH",k:"Bahrain"},
	{v:"BI",k:"Burundi"},
	{v:"BJ",k:"Benin"},
	{v:"BL",k:"Saint Barthélemy"},
	{v:"BM",k:"Bermuda"},
	{v:"BN",k:"Brunei Darussalam"},
	{v:"BO",k:"Bolivia"},
	{v:"BQ",k:"Bonaire, Sint Eustatius and Saba"},
	{v:"BR",k:"Brazil"},
	{v:"BS",k:"Bahamas"},
	{v:"BT",k:"Bhutan"},
	{v:"BV",k:"Bouvet Island"},
	{v:"BW",k:"Botswana"},
	{v:"BY",k:"Belarus"},
	{v:"BZ",k:"Belize"},
	{v:"CA",k:"Canada"},
	{v:"CC",k:"Cocos (Keeling) Islands"},
	{v:"CD",k:"Congo"},
	{v:"CF",k:"Central African Republic"},
	{v:"CG",k:"Congo"},
	{v:"CH",k:"Switzerland"},
	{v:"CI",k:"Côte d'Ivoire"},
	{v:"CK",k:"Cook Islands"},
	{v:"CL",k:"Chile"},
	{v:"CM",k:"Cameroon"},
	{v:"CN",k:"China"},
	{v:"CO",k:"Colombia"},
	{v:"CR",k:"Costa Rica"},
	{v:"CU",k:"Cuba"},
	{v:"CV",k:"Cabo Verde"},
	{v:"CW",k:"Curaçao"},
	{v:"CX",k:"Christmas Island"},
	{v:"CY",k:"Cyprus"},
	{v:"CZ",k:"Czechia"},
	{v:"DE",k:"Germany"},
	{v:"DJ",k:"Djibouti"},
	{v:"DK",k:"Denmark"},
	{v:"DM",k:"Dominica"},
	{v:"DO",k:"Dominican Republic"},
	{v:"DZ",k:"Algeria"},
	{v:"EC",k:"Ecuador"},
	{v:"EE",k:"Estonia"},
	{v:"EG",k:"Egypt"},
	{v:"EH",k:"Western Sahara"},
	{v:"ER",k:"Eritrea"},
	{v:"ES",k:"Spain"},
	{v:"ET",k:"Ethiopia"},
	{v:"FI",k:"Finland"},
	{v:"FJ",k:"Fiji"},
	{v:"FK",k:"Falkland Islands"},
	{v:"FM",k:"Micronesia"},
	{v:"FO",k:"Faroe Islands"},
	{v:"FR",k:"France"},
	{v:"GA",k:"Gabon"},
	{v:"GB",k:"United Kingdom"},
	{v:"GD",k:"Grenada"},
	{v:"GE",k:"Georgia"},
	{v:"GF",k:"French Guiana"},
	{v:"GG",k:"Guernsey"},
	{v:"GH",k:"Ghana"},
	{v:"GI",k:"Gibraltar"},
	{v:"GL",k:"Greenland"},
	{v:"GM",k:"Gambia"},
	{v:"GN",k:"Guinea"},
	{v:"GP",k:"Guadeloupe"},
	{v:"GQ",k:"Equatorial Guinea"},
	{v:"GR",k:"Greece"},
	{v:"GS",k:"South Georgia"},
	{v:"GT",k:"Guatemala"},
	{v:"GU",k:"Guam"},
	{v:"GW",k:"Guinea-Bissau"},
	{v:"GY",k:"Guyana"},
	{v:"HK",k:"Hong Kong"},
	{v:"HM",k:"Heard and McDonald Islands"},
	{v:"HN",k:"Honduras"},
	{v:"HR",k:"Croatia"},
	{v:"HT",k:"Haiti"},
	{v:"HU",k:"Hungary"},
	{v:"ID",k:"Indonesia"},
	{v:"IE",k:"Ireland"},
	{v:"IL",k:"Israel"},
	{v:"IM",k:"Isle of Man"},
	{v:"IN",k:"India"},
	{v:"IO",k:"British IOT"},
	{v:"IQ",k:"Iraq"},
	{v:"IR",k:"Iran"},
	{v:"IS",k:"Iceland"},
	{v:"IT",k:"Italy"},
	{v:"JE",k:"Jersey"},
	{v:"JM",k:"Jamaica"},
	{v:"JO",k:"Jordan"},
	{v:"JP",k:"Japan"},
	{v:"KE",k:"Kenya"},
	{v:"KG",k:"Kyrgyzstan"},
	{v:"KH",k:"Cambodia"},
	{v:"KI",k:"Kiribati"},
	{v:"KM",k:"Comoros"},
	{v:"KN",k:"Saint Kitts and Nevis"},
	{v:"KP",k:"North Korea"},
	{v:"KR",k:"South Korea"},
	{v:"KW",k:"Kuwait"},
	{v:"KY",k:"Cayman Islands"},
	{v:"KZ",k:"Kazakhstan"},
	{v:"LA",k:"Laos"},
	{v:"LB",k:"Lebanon"},
	{v:"LC",k:"Saint Lucia"},
	{v:"LI",k:"Liechtenstein"},
	{v:"LK",k:"Sri Lanka"},
	{v:"LR",k:"Liberia"},
	{v:"LS",k:"Lesotho"},
	{v:"LT",k:"Lithuania"},
	{v:"LU",k:"Luxembourg"},
	{v:"LV",k:"Latvia"},
	{v:"LY",k:"Libya"},
	{v:"MA",k:"Morocco"},
	{v:"MC",k:"Monaco"},
	{v:"MD",k:"Moldova"},
	{v:"ME",k:"Montenegro"},
	{v:"MF",k:"Saint Martin"},
	{v:"MG",k:"Madagascar"},
	{v:"MH",k:"Marshall Islands"},
	{v:"MK",k:"North Macedonia"},
	{v:"ML",k:"Mali"},
	{v:"MM",k:"Myanmar"},
	{v:"MN",k:"Mongolia"},
	{v:"MO",k:"Macao"},
	{v:"MP",k:"Northern Mariana Islands"},
	{v:"MQ",k:"Martinique"},
	{v:"MR",k:"Mauritania"},
	{v:"MS",k:"Montserrat"},
	{v:"MT",k:"Malta"},
	{v:"MU",k:"Mauritius"},
	{v:"MV",k:"Maldives"},
	{v:"MW",k:"Malawi"},
	{v:"MX",k:"Mexico"},
	{v:"MY",k:"Malaysia"},
	{v:"MZ",k:"Mozambique"},
	{v:"NA",k:"Namibia"},
	{v:"NC",k:"New Caledonia"},
	{v:"NE",k:"Niger"},
	{v:"NF",k:"Norfolk Island"},
	{v:"NG",k:"Nigeria"},
	{v:"NI",k:"Nicaragua"},
	{v:"NL",k:"Netherlands"},
	{v:"NO",k:"Norway"},
	{v:"NP",k:"Nepal"},
	{v:"NR",k:"Nauru"},
	{v:"NU",k:"Niue"},
	{v:"NZ",k:"New Zealand"},
	{v:"OM",k:"Oman"},
	{v:"PA",k:"Panama"},
	{v:"PE",k:"Peru"},
	{v:"PF",k:"French Polynesia"},
	{v:"PG",k:"Papua New Guinea"},
	{v:"PH",k:"Philippines"},
	{v:"PK",k:"Pakistan"},
	{v:"PL",k:"Poland"},
	{v:"PM",k:"Saint Pierre and Miquelon"},
	{v:"PN",k:"Pitcairn"},
	{v:"PR",k:"Puerto Rico"},
	{v:"PS",k:"Palestine, State of"},
	{v:"PT",k:"Portugal"},
	{v:"PW",k:"Palau"},
	{v:"PY",k:"Paraguay"},
	{v:"QA",k:"Qatar"},
	{v:"RE",k:"Réunion"},
	{v:"RO",k:"Romania"},
	{v:"RS",k:"Serbia"},
	{v:"RU",k:"Russian Federation"},
	{v:"RW",k:"Rwanda"},
	{v:"SA",k:"Saudi Arabia"},
	{v:"SB",k:"Solomon Islands"},
	{v:"SC",k:"Seychelles"},
	{v:"SD",k:"Sudan"},
	{v:"SE",k:"Sweden"},
	{v:"SG",k:"Singapore"},
	{v:"SH",k:"Saint Helena"},
	{v:"SI",k:"Slovenia"},
	{v:"SJ",k:"Svalbard and Jan Mayen"},
	{v:"SK",k:"Slovakia"},
	{v:"SL",k:"Sierra Leone"},
	{v:"SM",k:"San Marino"},
	{v:"SN",k:"Senegal"},
	{v:"SO",k:"Somalia"},
	{v:"SR",k:"Suriname"},
	{v:"SS",k:"South Sudan"},
	{v:"ST",k:"Sao Tome and Principe"},
	{v:"SV",k:"El Salvador"},
	{v:"SX",k:"Sint Maarten"},
	{v:"SY",k:"Syrian Arab Republic"},
	{v:"SZ",k:"Eswatini"},
	{v:"TC",k:"Turks and Caicos Islands"},
	{v:"TD",k:"Chad"},
	{v:"TF",k:"French Southern Territories"},
	{v:"TG",k:"Togo"},
	{v:"TH",k:"Thailand"},
	{v:"TJ",k:"Tajikistan"},
	{v:"TK",k:"Tokelau"},
	{v:"TL",k:"Timor-Leste"},
	{v:"TM",k:"Turkmenistan"},
	{v:"TN",k:"Tunisia"},
	{v:"TO",k:"Tonga"},
	{v:"TR",k:"Türkiye"},
	{v:"TT",k:"Trinidad and Tobago"},
	{v:"TV",k:"Tuvalu"},
	{v:"TW",k:"Taiwan"},
	{v:"TZ",k:"Tanzania"},
	{v:"UA",k:"Ukraine"},
	{v:"UG",k:"Uganda"},
	{v:"UM",k:"United States Minor Outlying Islands"},
	{v:"US",k:"United States of America"},
	{v:"UY",k:"Uruguay"},
	{v:"UZ",k:"Uzbekistan"},
	{v:"VA",k:"Holy See"},
	{v:"VC",k:"Saint Vincent and the Grenadines"},
	{v:"VE",k:"Venezuela"},
	{v:"VG",k:"Virgin Islands (British)"},
	{v:"VI",k:"Virgin Islands (U.S.)"},
	{v:"VN",k:"Vietnam"},
	{v:"VU",k:"Vanuatu"},
	{v:"WF",k:"Wallis and Futuna"},
	{v:"WS",k:"Samoa"},
	{v:"YE",k:"Yemen"},
	{v:"YT",k:"Mayotte"},
	{v:"ZA",k:"South Africa"},
	{v:"ZM",k:"Zambia"},
	{v:"ZW",k:"Zimbabwe"}
	];
}