DELIMITER $$
CREATE OR REPLACE FUNCTION Posts.GetMediaIdIfExists(
	p_sha256 BINARY(64)
)
RETURNS INT UNSIGNED
NOT DETERMINISTIC
READS SQL DATA
SQL SECURITY DEFINER
BEGIN
	RETURN (
		SELECT media_id
		FROM Posts.MediaMetadata
		WHERE hash_sha256 = p_sha256
		LIMIT 1
	);
END
$$
DELIMITER ;