
CREATE TABLE Posts.VVCache (
	id
		INT UNSIGNED NOT NULL
		REFERENCES Posts.Post(id),
	last_calc
		TIMESTAMP NOT NULL
		DEFAULT CURRENT_TIMESTAMP,

	view_total INT SIGNED NOT NULL,
	vote_total INT SIGNED NOT NULL,

	up INT UNSIGNED NOT NULL,
	up_yes INT UNSIGNED NOT NULL,
	up_ohno INT UNSIGNED NOT NULL,
	up_smart INT UNSIGNED NOT NULL,

	down INT UNSIGNED NOT NULL,
	down_cringe INT UNSIGNED NOT NULL,
	down_creep INT UNSIGNED NOT NULL,
	down_troll INT UNSIGNED NOT NULL,

	PRIMARY KEY(id)
) ENGINE=MEMORY;

