DELIMITER $$
CREATE OR REPLACE FUNCTION Actions.CreateFavFolder(
	p_user_id INT UNSIGNED,
	p_name TINYTEXT
)
RETURNS INT UNSIGNED
LANGUAGE SQL
NOT DETERMINISTIC
MODIFIES SQL DATA
SQL SECURITY DEFINER
BEGIN
	INSERT INTO Posts.UserFolders(user_id, name)
	VALUES (p_user_id, p_name);

	RETURN LAST_INSERT_ID();
END
$$
DELIMITER ;


-- DEPRECATED... Migrate All UserActions to Actions schema
DELIMITER $$
CREATE OR REPLACE FUNCTION Posts.CreateFavFolder(
	p_user_id INT UNSIGNED,
	p_name TINYTEXT
)
RETURNS INT UNSIGNED
LANGUAGE SQL
NOT DETERMINISTIC
MODIFIES SQL DATA
SQL SECURITY DEFINER
BEGIN
	SELECT Actions.CreateFavFolder(p_user_id, p_name);
END
$$
DELIMITER ;