CREATE DATABASE IF NOT EXISTS UserDB
	DEFAULT CHARACTER SET = utf8mb3;
CREATE DATABASE IF NOT EXISTS Posts
	DEFAULT CHARACTER SET = utf8mb3;
CREATE DATABASE IF NOT EXISTS Actions
	DEFAULT CHARACTER SET = utf8mb3;
CREATE DATABASE IF NOT EXISTS Comments
	DEFAULT CHARACTER SET = utf8mb3;
CREATE DATABASE IF NOT EXISTS Mods
	DEFAULT CHARACTER SET = utf8mb3;
