DELIMITER $$
CREATE OR REPLACE FUNCTION Posts.GetLinkByPostId(
	p_post_id INT UNSIGNED
)
RETURNS CHAR(12)
LANGUAGE SQL
NOT DETERMINISTIC
MODIFIES SQL DATA
SQL SECURITY DEFINER
BEGIN
	RETURN (
		SELECT link
		FROM Posts.Post
		WHERE id = p_post_id;
	)
END
$$
DELIMITER ;
