CREATE USER imgcat_jwt
IDENTIFIED BY 'imgcat_jwt'
WITH
	MAX_STATEMENT_TIME 1;

CREATE USER imgcat_posts
IDENTIFIED BY 'imgcat_posts'
WITH
	MAX_STATEMENT_TIME 5;

CREATE USER imgcat_mods
IDENTIFIED BY 'imgcat_mods'
WITH
	MAX_STATEMENT_TIME 5;

CREATE USER imgcat_system
IDENTIFIED BY 'imgcat_system'
WITH
	MAX_STATEMENT_TIME 5;