CREATE USER imgcat_jwt
IDENTIFIED BY GENERATED_DB_PASSWORD_JWT
WITH
	MAX_STATEMENT_TIME 1;

CREATE USER imgcat_posts
IDENTIFIED BY GENERATED_DB_PASSWORD_POSTS
WITH
	MAX_STATEMENT_TIME 5;

CREATE USER imgcat_mods
IDENTIFIED BY GENERATED_DB_PASSWORD_MODS
WITH
	MAX_STATEMENT_TIME 5;

CREATE USER imgcat_system
IDENTIFIED BY GENERATED_DB_PASSWORD_SYSTEM
WITH
	MAX_STATEMENT_TIME 5;